app = "franmalth"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  MIX_ENV = "prod"
  PHX_SERVER = "true"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
